---
# handlers file for flightaware
- name: Reboot host
  ansible.builtin.reboot:
    reboot_timeout: 600
    msg: "Rebooting to complete the flightaware installation."
    connect_timeout: 60
    pre_reboot_delay: 0
    post_reboot_delay: 30
    test_command: uptime
